### ISSUE TITLE
Display of Species Names

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#15]
Sometimes, names could be displayed in a better fashion. Take the example of [this tree](http://wellcaffeinated.net/Tree-of-Life/#/?ids=ott67244&ids=ott823917&ids=ott552587&ids=ott823920&ids=ott407108&ids=ott319864&ids=ott449378) where the six children names start with Limenitis. Seems like in some cases is way more important to show the last part of the name than the first part. For example seeing Arthemis, Astyanax, etc here would be more useful. We can:

- When there is no common name (as this case), we can use the double line for the scientific name (after all, we still can use this name.
- When the name is too long to fit, we can try to reduce all the first words, for example: "L. Astyanax" instead of "Limenitis Astyanax", and "L. A. Arthemis" instead of "Limenitis Arthemis Arthemis". All of this while keeping the full name when hovering over the card.
- Make a "Tall mode" that would work as the Wide mode, but will make all cards taller (3 or 4 lines, maybe?)

Also, what's the issue with the Red Spotted Admiral name here? Why it only shows "Red..."?
![image](https://user-images.githubusercontent.com/23618796/44886498-d8faf080-ac9c-11e8-8dd5-403bd0b33986.png)

**Comment by wellcaffeinated** [comment]
Is this better?
<img width="1293" alt="screen shot 2018-09-03 at 6 34 28 pm" src="https://user-images.githubusercontent.com/1128935/45002747-16ff5980-afa8-11e8-8f4a-0742216641eb.png">

**Comment by EverSalazar** [comment]
@wellcaffeinated YES! Way better. Now I'm wondering if we can make common names and scientific names more different, so that it is easily recognizable when common names aren't shown. The cursive is maybe too subtle? Wondering if just a smaller font for scientific names will do it.

Also, the space between lines can be a bit shorter. The current space works for separating Common and Scientific names but the space between "Vanessa" and "Atlanta" seems like too much.

I can't check, but if you hover over the text, does it show the entire name, right?

**Comment by wellcaffeinated** [comment]
I think we can close this one

**Comment by EverSalazar** [comment]
Yup, seems like this is solved nicely!
