### ISSUE TITLE
The Search Engine Problem

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#20]
So, it seems we need to figure out the search engine thing. I will be putting some ideas here:

1. Using Wikipedia's Search Engine: Is by far better at understanding humans than Wikidata or Wikispecies and every decent page have several taxon identifiers to pick from.
2. Using Google+Wikipedia: Searching things like "site:wikipedia.org chimpanzee GBIF" on Google, display nice results with their corresponding GBIF codes (though not all species/taxons will have GBIF codes, but maybe we can use NCBI and others?). Google searching works like wonders with partial searches too.
3. Using Google+OTL: Seems like Google hasn't mapped OTL website, because when I try to search, it doesn't work. If we find a way to use Google's power on OTL website, maybe we have our problem solved.
4. I just found out about [Taxize](https://ropensci.org/tutorials/taxize_tutorial/), which according to [their github page](https://github.com/ropensci/taxize), "allows users to search over many taxonomic data sources for species names (scientific and common) and download up and downstream taxonomic hierarchical information - among other things". Have you seen that before?
5. NCBI: Is there a particular reason why you picked GBIF over other taxonomic databases? Seems like NCBI search is a bit better than GBIF. Though it also has the Chimpanzee issue... I'm guessing that any of these databases is going to have an issue here and there? Maybe that's why we need something that is not restricted to a single database, like the case of Taxize or Google+Wikipedia.

**Comment by EverSalazar** [comment]
Yeah... that seems reasonable. There should be a way to quickly identify if
a particular taxon is in the tree or not, and if it's not, then remove it
from results.

**Comment by EverSalazar** [comment]
I think that you have solved this problem. At least, I don't think there are issues with the way it is implemented at the moment. Are you keeping this up for some reason @wellcaffeinated ? If not, then you can close it.

**Comment by wellcaffeinated** [comment]
Nope! I'll just close it
