### ISSUE TITLE
Expand branch

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#23]
Sometimes, I want to be able to expand al the children and children's children with one click, so I can explore a particular branch more easily. The OTL [does this automatically](https://tree.opentreeoflife.org/opentree/argus/opentree10.4@ott417969), it seems, always showing "two generations" for every taxon. would it be possible that on the drop down menu there is an option to show all children and grandchildren?

**Comment by wellcaffeinated** [comment]
Yup! i'll put this in

**Comment by EverSalazar** [comment]
Related comment from David:

> Relatedly, it would be cool to be able to click on a family or genus and instantly see all the species from it. Right now, it’s a ton of clicking to get to that point, which I assume is where lots of people want to be.
