### ISSUE TITLE
Common names are not always displayed on the info panel

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#27]
For example, the Western Pine Beetle (ott1017378) appears with both common and scientific name in the search results, but the common name is not displayed in the info panel.

![image](https://user-images.githubusercontent.com/23618796/46878866-cedf1c80-ce1a-11e8-9b88-da1d2f1cfa29.png)

![image](https://user-images.githubusercontent.com/23618796/46878871-d43c6700-ce1a-11e8-8933-1425e6ded1ae.png)

**Comment by wellcaffeinated** [comment]
For this case, it seems that OTL doesn't have any association to GBIF for that node, so i'd have to rewrite the search algorithm to search by scientific name... ugh... it would be much easier if they just linked these databases more consistently...

**Comment by EverSalazar** [comment]
I think this might be related to this problem. When expanding the list of species, "Metazoa" is listed, but when the card appears, it is named "Animalia". It seems that they're synonyms, so... there are some consistency issues there. Not sure if that needs fixing, but just in case you didn't know

![image](https://user-images.githubusercontent.com/23618796/46972198-5edbcb00-d094-11e8-92b4-5063d6b93604.png)

![image](https://user-images.githubusercontent.com/23618796/46972212-69966000-d094-11e8-8049-3bc94bd80b04.png)

**Comment by wellcaffeinated** [comment]
Ah good catch
