### ISSUE TITLE
Buttons stop working if the page is loaded or reloaded with URL tags set to 0

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#29]
So, for example, if you go to [this link](http://labs.minutelabs.io/Tree-of-Life-Explorer/#/?ids=ott332573&im=0&h=0&w=0) (notice the &im=0&h=0&w=0 part in it), none of the buttons will work. In general, whenever "im=0", "h=0", or "w=0" are in the URL, the buttons don't seem to identify them and thus they're not able to swap between states. If you manually change the URL, it works.

**Comment by wellcaffeinated** [comment]
yup! pushing a fix
