### ISSUE TITLE
"Share" button

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#32]
Comment from David:

> If the goal is to let people create cool trees and share them, we should make that easier to do so. They likely wont know they can copy and paste, since most things like this use ajax or something to make it impossible to do so. Maybe just make a big button somewhere that says “share this tree” that copies the url from above (and maybe even shrinks it so it’s more shareable). Might also be neat to let people write notes on their trees.

Not sure if integrating Twitter and FB social is easy (or effective), but at least a "Share this Tree" button will let people know that it's possible.

**Comment by wellcaffeinated** [comment]
I won't be able to shorten the url, but i could add a share button. Maybe it could just say "URL copied!" or something like that?

**Comment by EverSalazar** [comment]
Yes! that would totally work!
