### ISSUE TITLE
Populous Children Box issue

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#37]
From David:

> If you click on something with a lot of children, the text extends way below the box.

I have also noticed this from time to time, not only on children list but on branches list. It seems that with the changes to scrolling, you broke something on the lists since they don't scroll anymore and the full list is displayed on top of everything. For example, click on 34 [here](http://labs.minutelabs.io/Tree-of-Life-Explorer/#/?ids=ott770311&im=0&h=0&w=1)

**Comment by wellcaffeinated** [comment]
I think i fixed this just now, can you confirm?

**Comment by EverSalazar** [comment]
Yup, seems to be fixed now!
