### ISSUE TITLE
Not enough cat species

### ISSUE THREAD

**Issue by TitaniumSpyBorgBear** [minutelabsio/Tree-of-Life-Explorer#52]
So I was trying to find how related some of the Felinae cats are, only to find you've only included about 4 of them, which was disappointing, here's a few examples of ones you missed.
The pallas cat AKA Otocolobus manul
The entire genus of Leopardus which includes ocelots, oncillas and margays
The Caracal AKA Caracal caracal
The genus Catapuma
and many more.

**Comment by wellcaffeinated** [comment]
We actually don't host the data for the tree. The Open Tree of Life is a separate project and we use their data. They may have a reason for not including these taxa but that would be best discussed with them. Cheers!
