### ISSUE TITLE
Banana (Musa paradisiaca) failed with status code 400﻿

### ISSUE THREAD

**Issue by DarioViva42** [minutelabsio/Tree-of-Life-Explorer#54]
when I want to explore the Banana _Musa paradisiaca_
I get the fallowing Error Message:

> Error: Request failed with status code 400﻿

**Comment by DarioViva42** [comment]
Maybe it is because of the fact that this Musa is a hybrid.
Wikipedia [](https://en.wikipedia.org/wiki/Musa_×_paradisiaca)

> Musa × paradisiaca is the accepted name for the hybrid between Musa acuminata and Musa balbisiana.

**Comment by wellcaffeinated** [comment]
exactly right!
This is why it's not in the OTL database. It's not setup for hybrid species

**Comment by EverSalazar** [comment]
And this is precisely why exploring the tree is fascinating. You end up learning a lot of things about species

**Comment by DarioViva42** [comment]
The Strawberry _Fragaria ananassa_ has the same Problem as its a hybrid as well.

**Comment by DarioViva42** [comment]
thx for replying so quickly.
I would Imagine, that this would look very cool in the tree.
                 --musa balbisiana--
--musa--<                                 >--Musa paradisiaca--
                 --musa acuminata--

I would understand, if you dont want to implement this, as it is probably not that trivial.

But what you could do: Remove these Items from the autocompletion list,
as this gives wrong hopes that the species is in the System.

**Comment by wellcaffeinated** [comment]
Yes absolutely. Unfortunately we don't manage the data.

I was trying to remove the unfound species from the search but it's a bit tricky.
