### ISSUE TITLE
Cucurbita: the evil Jack O’Lantern

### ISSUE THREAD

**Issue by DarioViva42** [minutelabsio/Tree-of-Life-Explorer#55]
**GENUS** (e.g. Cucurbita) results in Error Code 400
**SUBSPECIES** (eg. Cucurbita okeechobeensis martinezii) results in Error Code 404

Unlike the Musa paradisiaca these are not hybrids, so I guess this should be easy to fix.
Maybe.

**Comment by DarioViva42** [comment]
oh and by the way:
Citrus × sinensis is also a hybrid, but doesn't Show as an hibrid in your app.
[Wikipedia](https://en.wikipedia.org/wiki/Orange_(fruit)#cite_note-AGLthesis-6):

> The orange is a hybrid between pomelo (Citrus maxima) and mandarin (Citrus reticulata).

**Comment by wellcaffeinated** [comment]
similar to #54 . we don't have control over the data unfortunately
