### ISSUE TITLE
Extinct species error 

### ISSUE THREAD

**Issue by bennonobueno** [minutelabsio/Tree-of-Life-Explorer#57]
I've tried this with Neanderthals and a few dinosaurs but whenever I search for an extinct species I get "Error: Request failed with status code 400" 
Now I'm not sure if extinct species are even supposed to work in this program but maybe then you should take their names out of the search bar. 
(Anyway, great tool. Love your work, keep it up!)

**Comment by wellcaffeinated** [comment]
This is related to #54 . That data isn't in the open tree of life unfortunately. Thanks though!
