### ISSUE TITLE
common name search not working

### ISSUE THREAD

**Issue by grahampcharles** [minutelabsio/Tree-of-Life-Explorer#59]
The UI leads me, a new user, to think that I can search for most or all known taxa, by common or Latin name. Here are a few that brought me no results (or incorrect ones, listed as partial Latin names):

* shark
* human
* cat 
* lion

Caveat: As a first-time user of the Tree of Life Explorer, I’m not entirely sure if this is a bug or a known limitation.

**Comment by wellcaffeinated** [comment]
Thanks for reporting this!
Looks like it might be a problem with the database service. I'm checking on it.
https://github.com/OpenTreeOfLife/opentree/issues/1192

**Comment by wellcaffeinated** [comment]
I found the issue. GBIF changed their data structure a bit. should work now
