### ISSUE TITLE
Undo/Redo options

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#6]
I know that in order to undo, you can go to previous page in the browser, but is it possible to assign "ctrl+Z" and "ctrl+shift+z" to previous page and next page, respectively?

**Comment by EverSalazar** [comment]
Hey @wellcaffeinated, Alex was intuitively pression ctrl+Z and ctrl+shift+Z in order to undo and redo... Is it possible to map those hotkeys to those functions? Or are they reserved? If not possible at all, feel free to close this again.

**Comment by wellcaffeinated** [comment]
I'd be a bit worried about someone typing in the search and using ctrl-z to get rid of the search term (which i do a lot)... but instead having it change the tree
