### ISSUE TITLE
OpenTree down

### ISSUE THREAD

**Issue by snacktavish** [minutelabsio/Tree-of-Life-Explorer#63]
http://opentreeoflife.github.io/
Just fyi - all OpenTree sites are down for the time being. Will update here when they are back up.

**Comment by wellcaffeinated** [comment]
@snacktavish Thanks for letting me know! Do you have an idea how long they'll be down? should i put up a notice on the ToLE?

**Comment by snacktavish** [comment]
Down time pretty unclear, we're investigating. Potentially tree_of_life and tnrs api calls (which as far as I can tell are all that the tree explorer uses) could be back up by tonight, but some other services will likely take longer. Logs suggest the minute labs tree explorer has been popular, so a note may be a good idea.

**Comment by snacktavish** [comment]
OpenTree is back up! Everything should be behaving normally - but we did update a bunch of stuff, so just let us know if you run into anything odd. Thanks!

**Comment by wellcaffeinated** [comment]
Perfect. thanks so much for your hard work!
