### ISSUE TITLE
I can't get inside the cat curated tree because of 400 bad request error

### ISSUE THREAD

**Issue by gavin357798089** [minutelabsio/Tree-of-Life-Explorer#68]
when you click the cat curated tree 400 bad request error appears

**Comment by EverSalazar** [comment]
This happens to me too, @wellcaffeinated. On Chrome, Firefox and Opera. And only when I click on the "cats" family. It doesn't even display the tree and it seems the problem is the second id in the URL (ids=ott532127), which makes the retrieving not work at all.

**Comment by wellcaffeinated** [comment]
Thanks. I have a few bugs to fix. I may have to take a day and go through all of them.
