### ISSUE TITLE
Chinese mountain cats 

### ISSUE THREAD

**Issue by gavin357798089** [minutelabsio/Tree-of-Life-Explorer#69]
Add Chinese mountain cats

**Comment by gavin357798089** [comment]
nevermind you just called them Chinese desert cats

**Comment by wellcaffeinated** [comment]
Thanks. I don't actually manage the content. It's managed by the Open Tree of Life team: https://tree.opentreeoflife.org/

**Comment by EverSalazar** [comment]
Also, if the species you're looking for doesn't appear on our explorer, you can always search for it at the Open Tree of Life and see why it isn't listed on the tree. Sometimes you'll find the the species is in the taxonomy, but not in the tree.

For example, in this case, if you search for "Felis bieti", the species listed in OTL is [Felis silvestris bieti](https://tree.opentreeoflife.org/taxonomy/browse?id=54743), which is in the Taxonomy and in the Tree (and thus is searchable under that name on the ToLE)
