### ISSUE TITLE
Dinosaurs not working

### ISSUE THREAD

**Issue by RedChaosScrungle** [minutelabsio/Tree-of-Life-Explorer#72]
Besides tyrannosaurus rex, it seems that putting in most dinosaurs doesn't work, I've tried velociraptor, therizinosaurus, even triceratops, none worked, so it'd be nice if you could fix that.

**Comment by EverSalazar** [comment]
This is related to #54. Unfortunately we are just pulling the tree info from the Open Tree of Life project and dinosaur phylogeny (their position on the tree) is almost impossible to determine with scientific precision. 

Thank you for using the Tree of Life Explorer and sharing this report.
