### ISSUE TITLE
Common names seems broken

### ISSUE THREAD

**Issue by rockwalrus** [minutelabsio/Tree-of-Life-Explorer#73]
Search by common name doesn't seem to work anymore. Even "dog", "cat", and "housecat" don't bring anything up.

**Comment by wellcaffeinated** [comment]
Thanks for letting us know! I'll look into this

**Comment by wellcaffeinated** [comment]
Looks like this is a bug upstream with GBIF
https://github.com/gbif/portal-feedback/issues/4238

**Comment by BurntVoxel** [comment]
They closed that bug, do you think that you need to update how you access their API?

https://github.com/gbif/portal-feedback/issues/4238#issuecomment-1243692284

> [marcos-lg](https://github.com/marcos-lg) commented [8 days ago (September 12)](https://github.com/gbif/portal-feedback/issues/4238#issuecomment-1243692284): 
> >  Fixed in PROD.
> 
> [marcos-lg](https://github.com/marcos-lg) marcos-lg closed this as [completed](https://github.com/gbif/portal-feedback/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [8 days ago (September 12)](https://github.com/gbif/portal-feedback/issues/4238#event-7367216138)

**Comment by lackeyd** [comment]
I'm having the same problem, still today.

**Comment by wellcaffeinated** [comment]
I think this has been fixed. If there are any other problems let me know!

**Comment by lackeyd** [comment]
Confirmed!

Thank you for letting me know,

Dennis Lackey
*Chemistry & Zoology Teacher*
*I Am Reading: Get in Trouble by Kelly Link*

**Comment by wnxkitchenaid** [comment]
> I think this has been fixed. If there are any other problems let me know!

I'm seeing the issue of common names not working today (12/7/2022).

**Comment by EverSalazar** [comment]
I can confirm that search by common names isn't working @wellcaffeinated

**Comment by EverSalazar** [comment]
Seems like only the **search function** in ToLE isn't working with common names, since once the cards are displayed, they do show common names and links and everything work as usual. Maybe it's something related with the API only when searching @wellcaffeinated ?

**Comment by wellcaffeinated** [comment]
Yeah it's the gbif api again. I've poked them about it to see if there's anything they can do

**Comment by wellcaffeinated** [comment]
Looks like it's fixed again!
