### ISSUE TITLE
Images on Parent Cards

### ISSUE THREAD

**Issue by EverSalazar** [minutelabsio/Tree-of-Life-Explorer#9]
Right now, "Felidae" displays the same image as "Panthera Tigris", which can be confusing. Not sure what to do in these cases, but it feels right that Felidae has some sort of picture when it's not displaying any children, but maybe when it is displaying children, then remove the image? (maybe that would make things inconsistent or less smooth)... Or maybe find a way to indicate that the picture displayed is from a children? The Carnivora card seems to diplay several animals at the same time, which might be a good solution too, even if they're not individually recognizable. It seems that this is happening since the image pulled is actually a collage of images, but not sure where it is pulling it from, since the Wikipedia page for Felidae is also a collage.

![image](https://user-images.githubusercontent.com/23618796/44881315-90840880-ac85-11e8-96ad-335d356a68e6.png)

**Comment by wellcaffeinated** [comment]
Yeah... it's tricky. The problem is I can't write any way to "know" what the images will be...
I've made an update that tries to make a collage if it can, especially for MRCAs. Hopefully the images make sense. It would be helpful for you to take a look and see if the collages work...

**Comment by EverSalazar** [comment]
Yes, I think it works better. But I wouldn't worry too much about this issue at this point. 

It appears that the higher a taxon is, the less relevant the image is. For example, what image or images are taxons like Bilateria or Sauropsida supposed to display? I'm inclined to think that maybe only the species (and maybe direct parents) should have pictures... but not sure... I'd say that this is not important for MVA (Minimum Viable App)

**Comment by EverSalazar** [comment]
I got a comment from a friend saying that Pan (ott417957) displayed images of statues and roman buildings: 
![image](https://user-images.githubusercontent.com/23618796/46972594-31435180-d095-11e8-9aa3-dac82ed60e47.png)

And is making me wonder about what the solution to this issue could be. Putting several images on a card makes them look way too busy and I think that I'm inclined to go for a single image every time. However, only cards that are not displaying children should have pictures on them (in order to avoid the confusing case of the tiger pointed at the beginning of this thread)

I'm not sure about this though... would it be possible to curate only some images and leave vast majority algorithmic? I'm thinking on overriding some of the algorithmically chosen images with our own links that we determine are better.

**Comment by wellcaffeinated** [comment]
Unfortunately there's no easy way to analyze an image programatically. But maybe I could only show images species/subspecies/families ??

**Comment by EverSalazar** [comment]
I think that might work. Restricting the display of images to the near-tips
would at least remove the issue of deciding what to display on upper parent
cards.
